version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "02:00"
    open-pull-requests-limit: 10
    assignees:
      - peaky76
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    groups:
      dev-dependencies:
        dependency-type: "development"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
    open-pull-requests-limit: 10
