name: Build & Deploy
on:
  push:
    branches: [master]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy handykapp-etl
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          run: ./.github/scripts/clone.sh
          shell: bash |
            
