name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3

      - name: Install dependencies
        run: poetry install
