name: Build & Deploy
on:
  push:
    branches: [master]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy handykapp-etl
        uses: appleboy/ssh-action@v.0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          
          script: |
            mkdir handykapp-etl
            cd handykapp-etl
            git clone git@github.com:peaky76/handykapp-etl.git
            echo 'Deployment successful to Digital Ocean'
