name: Build & Deploy
on:
  push:
    branches: [master]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into remote
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}          
          script_stop: true
          script: |
            cd handykapp-etl && git pull git@github.com:peaky76/handykapp-etl.git
            poetry lock
            poetry install  
            echo 'Deployment successful to Digital Ocean'
